### PR TITLE
Minify css js

### PR DESCRIPTION
**Pull request by morekid**
@davidmytton moved minification to this branch with also adding it for JS.

Additionally I've added fingerprinting to the filenames so that we reduce caching issue.

Let me know what you think.

### CODE REVIEW

**Comment by davidmytton** [comment]
@morekid FYI b894096 adds `new.css` back in because we host it for use on the Mailchimp hosted pages, like subscribe confirmation.

**Comment by davidmytton** [comment]
Rebased to `main`

**Comment by davidmytton** [comment]
Issue seems to be that in switching color schemes, it's only changing `dark` for `light` without also referencing the content hash for the CSS path. E.g. `GET https://console.dev/css/style-dark.min.c70101a0629041f0f1de5696c25b8342a6ad2ca5aa06d69a82ffd9239865c69d.css` but `c70101a0629041f0f1de5696c25b8342a6ad2ca5aa06d69a82ffd9239865c69d` is the hash for the light theme.

**Comment by morekid** [comment]
@davidmytton pushed a fix for the theme switching bug. I was rebuilding the stylesheet url without considering the fingerprint, I'm now always taking the url from the preload link.

**Pull request merged**
