### PR TITLE
Images performance

### PR DESCRIPTION
**Pull request by morekid**
@davidmytton here's the work on images, does two things:

- adds `loading="lazy"` to optimize image load.
- refactor to `parseTools.py` and list thumbnails rendering to scale images using Hugo resource pipes.
- Serve next gen format `.webp` where possible.

If the approach works we can later on transition to Hugo resizing and webp elsewhere on the site.

### CODE REVIEW

**Comment by davidmytton** [comment]
Looks good so far.

The favicons were duplicated in `static/img/favicons` and `assets/img/favicons` so 8476912 removes the former. I assume that is fine now all the favicons are being downloaded there?

I also handled an edge case for Sourcegraph where the image doesn't compress well with the Calibre action used - see 9883fe6 - however, can we now remove that action from the build step if Hugo is doing the compression/optimization as part of its build?

**Comment by davidmytton** [comment]
Also seems to be an issue with some of the images missing, but not all (and they are present on disk):

image

**Comment by morekid** [comment]
@davidmytton thanks for spotting these. Forgot to remove the old favicons folder.

For sourcegraph, can we check that's still the case? I converted a few cases of images that had `.png` extension but where really other formats underneath (sourcegraph was `.ico`), see [this](https://github.com/consoledotdev/home/pull/179/commits/3bdbb087a2572c426224957ca5c9d08ede7988c5).
There's an ICO extractor script [here](https://github.com/consoledotdev/home/pull/179/files#diff-378860d54f8fb63e5ae1abfcf58a34d6d9982ed8729107cd6f01c65fc70cd1c9) that I used for conversion (require [ImageMagick](https://imagemagick.org/index.php))

I couldn't replicate the issue in the interviews page, will check a bit more.

I'd leave the compression step in, for resized images the saving is small but stil exists + not all images are small or properly resized so compressing them will be useful.

**Comment by davidmytton** [comment]
Yeah you can see in 3bdbb087a2572c426224957ca5c9d08ede7988c5 that the output is blurred. I've dropped in a PNG saved from their Twitter account - 9883fe6 - so that might be solved now. I'll remove the exclusion from the Calibre compression action and see what it does.

**Comment by davidmytton** [comment]
d5a5916 looks ok!

**Comment by morekid** [comment]
@davidmytton will be pushing some fixes to edge cases (like `.jpeg` and `.jpg` handling), and also looking at the interviews page.

**Comment by morekid** [comment]
@davidmytton good to go from my side, this refactors image use in many places so worth an in-depth look.

**Pull request merged**
