### PR TITLE
Style library

### PR DESCRIPTION
**Pull request by morekid**
A number of updates:
- Creates a Design Library page (icons + color so far).
- Partials for all Icons.
- Updates icons usage everywhere.
- Other minor fixes for partials reuse.

### CODE REVIEW

**Comment by davidmytton** [comment]
Is the send icon supposed to be black in light mode?

screenshot_1615827083

**Comment by davidmytton** [comment]
The GitHub icon is also slightly misaligned:

Before

screenshot_1615827163

After

screenshot_1615827157

**Comment by morekid** [comment]
@davidmytton both look good for me, perhaps a caching issue?

**Comment by davidmytton** [comment]
Yeah you're right - all looks good now.

**Pull request merged**
